---
- name: Install brew apps and AppStore apps on macOS
  hosts: localhost
  connection: local

  vars:
    mas_installed_apps:
      - 1569813296  # 1Password for Safari
      - 1168254295  # AmorphousDiskMark
      - 937984704   # Amphetamine
      - 402670023   # Keyboard Pilot
      - 540348655   # Monosnap

    homebrew_cask_accept_external_apps: true

    homebrew_taps:
      # sshpass
      - { name: esolitos/ipa, url: 'https://github.com/esolitos/homebrew-ipa' }
      # vagrant/terraform
      - { name: hashicorp/tap, url: 'https://github.com/hashicorp/homebrew-tap' }

    homebrew_installed_packages:
      - ansible-lint
      - colima
      - docker
      - docker-compose
      - git
      - git-crypt
      - git-lfs
      - grep
      - iperf3
      - jq
      - sshpass
      - terraform
      - wget
      - yq
      - yamllint
      - ssh-copy-id
      - pv
      - zsh
      # - oh-my-zsh
      # - zsh auto-complete


    homebrew_cask_apps:
      - firefox
      - google-chrome
      - vlc
      - hashicorp-vagrant
      - keka
      - kekaexternalhelper
      - macfuse
      - session-manager-plugin
      - telegram-desktop
      - utm
      - vagrant
      - rambox
      - visual-studio-code@insiders
      - visual-studio-code
      # - forklift
      - maccy
      - deepl
      - rectangle
      - iterm2
      - appcleaner
      - multitouch
      - blueharvest
      - finicky
      - tunnelblick
      # - epic pen
      - jordanbaird-ice
      - macupdater
      - audio-hijack
      - loopback
      - vnc-viewer
      - 1password
      - bitwarden
      - deltawalker
      - obsidian
      - brave-browser
      # - zscaler

    dockitems_remove:
      - Launchpad
      - Safari
      - Messages
      - Mail
      - Maps
      - Photos
      - FaceTime
      - Calendar
      - Contacts
      - Reminders
      - Notes
      - Freeform
      - TV
      - Music
      - Keynote
      - Numbers
      - Pages
      - News
      - 'App Store'

    dockitems_persist:
      - name: Rambox
        path: "/Applications/Rambox.app/"
      - name: "Telegram Desktop"
        path: "/Applications/Telegram Desktop.app/"
      - name: Firefox
        path: "/Applications/Firefox.app/"
      - name: Google Chrome
        path: "/Applications/Google Chrome.app/"
      - name: Visual Studio Code
        path: "/Applications/Visual Studio Code.app/"
      - name: Visual Studio Code Insiders
        path: "/Applications/Visual Studio Code - Insiders.app/"
      - name: iTerm2
        path: "/Applications/iTerm.app/"

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags:
        - cli-tools
    - role: homebrew # geerlingguy.mac.homebrew
      tags:
        - homebrew
    - role: geerlingguy.mac.mas
      tags:
        - mas
    - role: geerlingguy.mac.dock
      tags:
        - dock